name: Node CI Pull request
concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: run all checks and get coverage
        run: pnpm run all-checks
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: packages/rooks/src/coverage
  # size-limit:
  #   timeout-minutes: 20
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/ci-setup
  #     - uses: andresz1/size-limit-action@v1.7.0
  #       with:
  #         directory: "packages/rooks"
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
